(() => {
  "use strict";
  const W = 8, FOV = Math.PI / 3, MAX = 12, FIXED = 1 / 60;
  const VOICE_DEFAULT = { low: 500, high: 5000 }, HRTF_DEFAULT = { low: 260, high: 1200 };
  const sceneCanvas = document.querySelector("#scene"), sceneCtx = sceneCanvas.getContext("2d");
  const povCanvas = document.querySelector("#pov"), povCtx = povCanvas.getContext("2d");
  const $ = id => document.getElementById(id);
  const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
  const wrap = a => { while (a > Math.PI) a -= Math.PI * 2; while (a < -Math.PI) a += Math.PI * 2; return a; };
  const deg = r => r * 180 / Math.PI, rad = d => d * Math.PI / 180;
  const clone = value => JSON.parse(JSON.stringify(value));
  const shapeSizes = { circle: [0.65, 0.65, 1.2], cube: [1.1, 1.1, 1.1], person: [0.55, 0.4, 1.75], car: [1.8, 4, 1.45] };
  const assetNames = { circle: ["circle"], cube: ["cube"], person: ["person-front", "person-front45", "person-profile", "person-rear45", "person-rear"], car: ["car-front", "car-front45", "car-profile", "car-rear45", "car-rear"] };
  const assets = {};
  for (const key of Object.keys(assetNames)) for (const name of assetNames[key]) { const img = new Image(); img.src = `assets/obstacles/${name}.png`; assets[name] = img; }

  const defaults = { schemaVersion: 2, listener: { x: 0, z: 0, heading: 0 }, obstacles: [makeObstacle("A", "circle", 0, 4)], selected: "A", paused: false, mode: "baseline", frequencies: { voiceLow: 500, voiceHigh: 5000, hrtfLow: 260, hrtfHigh: 1200 } };
  const state = clone(defaults); state.obstacles[0].prevDistance = 4;
  const sim = { last: performance.now(), accumulator: 0, keys: new Set(), drag: null, log: [], sample: 0, eventLogOpen: false };
  function makeObstacle(id, shape, x, z) { const s = shapeSizes[shape]; return { id, label: id, shape, x, z, heading: 0, widthM: s[0], depthM: s[1], heightM: s[2], audible: true, prevDistance: Math.hypot(x, z), motion: { type: "stationary", phase: 0, direction: 1, speedMps: .6, startX: x, startZ: z, endX: x, endZ: z, centerX: 0, centerZ: 0, radiusM: 3, angularSpeedDeg: 20, stopDistanceM: .7 } }; }
  function log(type, data = {}) { sim.log.push({ t: +(performance.now() / 1000).toFixed(3), type, mode: state.mode, ...data }); if (sim.log.length > 500) sim.log.shift(); }
  function current() { return state.obstacles.find(o => o.id === state.selected) || null; }
  function nextId() { for (let i = 0; i < MAX; i++) { const id = String.fromCharCode(65 + i); if (!state.obstacles.some(o => o.id === id)) return id; } return null; }
  function validScene(candidate) {
    if (!candidate || candidate.schemaVersion !== 2 || !candidate.listener || !Array.isArray(candidate.obstacles) || candidate.obstacles.length > MAX) throw new Error("Invalid scene file");
    const ids = new Set(); const allowedShapes = new Set(Object.keys(shapeSizes)); const allowedMotion = new Set(["stationary", "patrol", "orbit", "approach"]);
    for (const o of candidate.obstacles) { if (!o.id || ids.has(o.id) || !allowedShapes.has(o.shape) || !allowedMotion.has(o.motion?.type)) throw new Error("Invalid obstacle definition"); ids.add(o.id); for (const n of [o.x, o.z, o.heading, o.widthM, o.depthM, o.heightM]) if (!Number.isFinite(n)) throw new Error("Non-finite scene value"); }
    return candidate;
  }
  function resetScene() { const wasAudio = audio.started; Object.assign(state, clone(defaults)); state.obstacles[0].prevDistance = 4; state.selected = "A"; sim.keys.clear(); sim.drag = null; audio.sync(); if (wasAudio) audio.resume(); log("reset", { obstacleCount: 1 }); renderAll(); }
  function addObstacle(source) { if (state.obstacles.length >= MAX) return; const id = nextId(); const o = source ? clone(source) : makeObstacle(id, "box", (state.obstacles.length % 3 - 1) * 2, -2 - state.obstacles.length); o.id = id; o.label = id; o.prevDistance = Math.hypot(o.x - state.listener.x, o.z - state.listener.z); state.obstacles.push(o); state.selected = id; log("obstacle_added", { obstacleId: id }); renderAll(); }
  function removeObstacle() { const o = current(); if (!o) return; state.obstacles = state.obstacles.filter(x => x.id !== o.id); state.selected = state.obstacles.at(-1)?.id || null; audio.sync(); log("obstacle_removed", { obstacleId: o.id }); renderAll(); }
  function duplicateObstacle() { const o = current(); if (!o) return; const copy = clone(o); copy.x = clamp(copy.x + .8, -W + .25, W - .25); copy.z = clamp(copy.z + .8, -W + .25, W - .25); addObstacle(copy); }
  function patchObstacle(key, value) { const o = current(); if (!o) return; if (["x", "z", "heading", "widthM", "depthM", "heightM"].includes(key)) value = Number(value); if (key === "shape" && shapeSizes[value]) { o.shape = value; [o.widthM, o.depthM, o.heightM] = shapeSizes[value]; } else if (key === "label") o.label = String(value).slice(0, 12); else if (key === "audible") o.audible = Boolean(value); else if (key === "motion") o.motion.type = value; else o[key] = value; o.x = clamp(o.x, -W + .25, W - .25); o.z = clamp(o.z, -W + .25, W - .25); log("obstacle_updated", { obstacleId: o.id, key }); audio.sync(); renderAll(); }
  function motionPatch(key, value) { const o = current(); if (!o) return; o.motion[key] = Number(value); if (key === "type") o.motion.type = value; log("motion_changed", { obstacleId: o.id, key }); renderAll(); }
  function updateMotion(o, dt) {
    if (state.paused || o.motion.type === "stationary") return;
    const m = o.motion, speed = Math.max(0, Number(m.speedMps) || 0);
    if (m.type === "patrol") { const dx = m.endX - m.startX, dz = m.endZ - m.startZ, len = Math.hypot(dx, dz) || 1; m.phase += m.direction * speed * dt / len; if (m.phase >= 1) { m.phase = 1; m.direction = -1; } if (m.phase <= 0) { m.phase = 0; m.direction = 1; } o.x = m.startX + dx * m.phase; o.z = m.startZ + dz * m.phase; }
    if (m.type === "orbit") { m.phase += rad(Number(m.angularSpeedDeg) || 0) * dt; o.x = Number(m.centerX) + Math.cos(m.phase) * Number(m.radiusM); o.z = Number(m.centerZ) + Math.sin(m.phase) * Number(m.radiusM); }
    if (m.type === "approach") { const dx = state.listener.x - o.x, dz = state.listener.z - o.z, d = Math.hypot(dx, dz) || 1, stop = Number(m.stopDistanceM) || .7, step = Math.min(speed * dt, Math.max(0, d - stop)); o.x += dx / d * step; o.z += dz / d * step; }
    o.x = clamp(o.x, -W + .25, W - .25); o.z = clamp(o.z, -W + .25, W - .25);
  }
  function metrics(o) { const dx = o.x - state.listener.x, dz = o.z - state.listener.z, distance = Math.hypot(dx, dz), worldAngle = Math.atan2(dx, dz), relativeAzimuth = wrap(worldAngle - state.listener.heading); return { dx, dz, distance, worldAngle, relativeAzimuth, radialVelocity: o.prevDistance - distance, pan: clamp(relativeAzimuth / (Math.PI / 2), -1, 1) }; }
  function worldToRadar(x, z) { const relativeX = x - state.listener.x, relativeZ = z - state.listener.z; return { x: sceneCanvas.width / 2 + relativeX * sceneCanvas.width / (W * 2), y: sceneCanvas.height / 2 - relativeZ * sceneCanvas.width / (W * 2) }; }
  function rotatedFootprint(o) { const hw = o.widthM / 2, hd = o.depthM / 2, c = Math.cos(rad(o.heading)), s = Math.sin(rad(o.heading)); return [[-hw,-hd],[hw,-hd],[hw,hd],[-hw,hd]].map(([x,z]) => ({ x: x*c - z*s + o.x, z: x*s + z*c + o.z })); }
  function drawFootprint(o) { const p = worldToRadar(o.x, o.z), scale = sceneCanvas.width / (W * 2); sceneCtx.save(); sceneCtx.translate(p.x, p.y); sceneCtx.rotate(-rad(o.heading)); const w = o.widthM * scale, h = o.depthM * scale; sceneCtx.beginPath(); if (o.shape === "circle") sceneCtx.arc(0, 0, Math.max(8, w / 2), 0, Math.PI * 2); else if (o.shape === "person") { sceneCtx.rect(-w/2, -h/2, w, h); sceneCtx.arc(0, -h*.32, w*.38, 0, Math.PI*2); } else if (o.shape === "car") { sceneCtx.roundRect(-w/2, -h/2, w, h, Math.min(w,h)*.18); } else sceneCtx.rect(-w/2, -h/2, w, h); sceneCtx.fillStyle = "#111"; sceneCtx.fill(); sceneCtx.restore(); }
  function drawRadar() { const c = sceneCtx, s = sceneCanvas.width / (W * 2); c.clearRect(0, 0, sceneCanvas.width, sceneCanvas.height); c.strokeStyle = "#ddd"; c.lineWidth = 1; for (let r = 1; r <= 8; r++) { c.beginPath(); c.arc(sceneCanvas.width/2, sceneCanvas.height/2, r*s, 0, Math.PI*2); c.stroke(); } c.strokeStyle = "#999"; c.beginPath(); c.moveTo(sceneCanvas.width/2,0); c.lineTo(sceneCanvas.width/2,sceneCanvas.height); c.moveTo(0,sceneCanvas.height/2); c.lineTo(sceneCanvas.width,sceneCanvas.height/2); c.stroke(); const f = { x: Math.sin(state.listener.heading), z: Math.cos(state.listener.heading) }; c.strokeStyle = "#111"; c.lineWidth = 3; c.beginPath(); c.moveTo(sceneCanvas.width/2,sceneCanvas.height/2); c.lineTo(sceneCanvas.width/2 + f.x*35, sceneCanvas.height/2 - f.z*35); c.stroke(); c.fillStyle = "#fff"; c.strokeStyle = "#111"; c.lineWidth = 2; c.beginPath(); c.arc(sceneCanvas.width/2,sceneCanvas.height/2,12,0,Math.PI*2); c.fill(); c.stroke(); for (const o of state.obstacles) { drawFootprint(o); const p = worldToRadar(o.x,o.z); c.fillStyle="#111"; c.font="12px ui-monospace"; c.fillText(o.label,p.x+14,p.y-12); } }
  function viewIndex(o, m) { if (o.shape === "circle" || o.shape === "cube") return 0; let relative = wrap(rad(o.heading) - (m.worldAngle + Math.PI)); let abs = Math.abs(relative); let i = Math.round(abs / (Math.PI / 4)); return clamp(i, 0, 4); }
  function drawPovAsset(o, m, x, y, width, height) { const name = assetNames[o.shape][viewIndex(o,m)], img = assets[name]; if (!img || !img.complete) return false; povCtx.save(); const relative = wrap(rad(o.heading) - (m.worldAngle + Math.PI)); if (relative < 0 && o.shape !== "circle" && o.shape !== "cube") { povCtx.translate(x + width, y); povCtx.scale(-1,1); povCtx.drawImage(img,0,0,width,height); } else povCtx.drawImage(img,x,y,width,height); povCtx.restore(); return true; }
  function drawPov() { const c=povCtx,w=povCanvas.width,h=povCanvas.height,horizon=h*.58; c.clearRect(0,0,w,h); c.strokeStyle="#ddd"; c.lineWidth=1; c.beginPath(); c.moveTo(0,horizon);c.lineTo(w,horizon); for(let i=1;i<8;i++){const x=w*i/8;c.moveTo(x,horizon);c.lineTo(w/2+(x-w/2)*.2,h);} for(let i=1;i<5;i++){const y=horizon+(h-horizon)*i/5;c.moveTo(0,y);c.lineTo(w,y)} c.stroke(); const list=state.obstacles.map(o=>({o,m:metrics(o)})).filter(x=>Math.abs(x.m.relativeAzimuth)<FOV/2 && x.m.distance>.1).sort((a,b)=>b.m.distance-a.m.distance); for(const {o,m} of list){const x=w/2+Math.tan(m.relativeAzimuth)/(2*Math.tan(FOV/2))*w;const height=Math.min(clamp(310/Math.max(.25,m.distance),18,horizon-8),horizon-8);const width=clamp(height*(o.widthM/Math.max(.2,o.heightM)),12,w*1.6);drawPovAsset(o,m,x-width/2,horizon-height,width,height);c.fillStyle="#111";c.font="12px ui-monospace";c.fillText(o.label,x+width/2+4,horizon-height+12)} if(!list.length){c.fillStyle="#666";c.font="12px ui-monospace";c.fillText("no obstacle in 60 deg view",12,h-14)} if(state.mode==="baseline"&&audio.started){const sweepX=clamp(audio.sweepPhase,0,1)*w;c.strokeStyle="#2d6cdf";c.lineWidth=2;c.beginPath();c.moveTo(sweepX,horizon);c.lineTo(sweepX,h);c.stroke()} }
  function voiceRange(){return {low:state.frequencies.voiceLow,high:state.frequencies.voiceHigh}} function hrtfRange(){return {low:state.frequencies.hrtfLow,high:state.frequencies.hrtfHigh}};
  function buildVoiceImage(){const image=new Uint8Array(64*64);for(const o of state.obstacles){const m=metrics(o);if(Math.abs(m.relativeAzimuth)>FOV/2)continue;const x=Math.round((m.relativeAzimuth/FOV+.5)*63), y=48, r=Math.round(clamp(18/m.distance,2,18)), level=clamp(Math.round(15-m.distance),1,15);for(let yy=y-r;yy<=y+r;yy++)for(let xx=x-r;xx<=x+r;xx++){if(xx<0||xx>=64||yy<0||yy>=64)continue;const fall=1-Math.hypot(xx-x,yy-y)/(r+.5);if(fall>0)image[yy*64+xx]=Math.max(image[yy*64+xx],Math.round(level*fall))}}return image}
  const audio={ctx:null,master:null,voices:new Map(),started:false,baseline:null,async start(){if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=.36;this.master.connect(this.ctx.destination);this.sync()}await this.ctx.resume();this.started=true;syncAudioButton();log("audio_started",{sampleRate:this.ctx.sampleRate})},async stop(){if(!this.ctx)return;for(const v of this.voices.values())v.gain.gain.setTargetAtTime(.0001,this.ctx.currentTime,.01);if(this.baseline){try{this.baseline.stop()}catch{}}await this.ctx.suspend();this.started=false;syncAudioButton();log("audio_stopped")},async resume(){if(this.ctx&&this.started)await this.ctx.resume()},sync(){if(!this.ctx)return;const ids=new Set(state.obstacles.filter(o=>o.audible).map(o=>o.id));for(const [id,v] of this.voices){if(!ids.has(id)){try{v.osc.stop()}catch{};this.voices.delete(id)}}for(const o of state.obstacles)if(o.audible&&!this.voices.has(o.id)){const osc=this.ctx.createOscillator(),gain=this.ctx.createGain(),p=this.ctx.createPanner();p.panningModel="HRTF";p.distanceModel="inverse";p.refDistance=1;p.maxDistance=30;osc.type="sine";osc.frequency.value=500;gain.gain.value=.0001;osc.connect(gain).connect(p).connect(this.master);osc.start();this.voices.set(o.id,{osc,gain,p})}},update(){if(!this.ctx||!this.started)return;const now=this.ctx.currentTime;if(state.mode==="baseline"){for(const v of this.voices.values())v.gain.gain.setTargetAtTime(.0001,now,.02);if(!this.baseline||this.baseline.ended){const source=this.ctx.createBufferSource();source.buffer=makeVoiceBuffer(buildVoiceImage());source.connect(this.master);source.start();this.baseline=source;source.onended=()=>{if(this.baseline===source)this.baseline.ended=true}}return}if(this.baseline){try{this.baseline.stop()}catch{};this.baseline=null}const count=Math.max(1,state.obstacles.filter(o=>o.audible).length),gainScale=1/Math.sqrt(count);for(const o of state.obstacles){const v=this.voices.get(o.id);if(!v)continue;const m=metrics(o),pos={x:o.x,y:0,z:-o.z};v.p.positionX.value=pos.x;v.p.positionY.value=0;v.p.positionZ.value=pos.z;v.gain.gain.setTargetAtTime(o.audible?gainScale*clamp(1/(.5+m.distance),.03,.8):.0001,now,.03);const t=clamp((Math.cos(m.relativeAzimuth)+1)/2,0,1);v.osc.frequency.setTargetAtTime(hrtfRange().low*Math.pow(hrtfRange().high/hrtfRange().low,t),now,.03)}}};
  function makeVoiceBuffer(image){const sr=audio.ctx.sampleRate||44100,count=Math.floor(sr*1.05),b=audio.ctx.createBuffer(2,count,sr),l=b.getChannelData(0),r=b.getChannelData(1),phases=Array.from({length:64},(_,i)=>i*.71),freq=Array.from({length:64},(_,i)=>2*Math.PI*voiceRange().high*Math.pow(voiceRange().low/voiceRange().high,i/63));for(let k=0;k<count;k++){const col=Math.min(63,Math.floor(k/count*64)),pan=col/63*2-1,t=k/sr;let s=0;for(let row=0;row<64;row++){const a=image[row*64+col];if(a)s+=Math.pow(10,(a-15)/20)*Math.sin(freq[row]*t+phases[row])}s*=.018;l[k]=s*(1-pan*.45);r[k]=s*(1+pan*.45)}return b}
  function syncHrtfListener(){if(!audio.ctx||!audio.started)return;const listener=audio.ctx.listener,forward={x:Math.sin(state.listener.heading),z:Math.cos(state.listener.heading)};if("positionX" in listener){listener.positionX.value=state.listener.x;listener.positionY.value=0;listener.positionZ.value=-state.listener.z;listener.forwardX.value=forward.x;listener.forwardY.value=0;listener.forwardZ.value=-forward.z;listener.upX.value=0;listener.upY.value=1;listener.upZ.value=0}else if(listener.setPosition){listener.setPosition(state.listener.x,0,-state.listener.z);listener.setOrientation(forward.x,0,-forward.z,0,1,0)}}
  function syncAudioButton(){const b=$("startAudio");b.textContent=audio.started?"Stop Audio":"Start Audio";b.dataset.audioState=audio.started?"playing":"stopped"}
  function syncRanges(){$("voiceLow").value=state.frequencies.voiceLow;$('voiceHigh').value=state.frequencies.voiceHigh;$('hrtfLow').value=state.frequencies.hrtfLow;$('hrtfHigh').value=state.frequencies.hrtfHigh}
  function renderList(){const el=$("obstacleList");el.innerHTML="";for(const o of state.obstacles){const row=document.createElement("div");row.className=`obstacle-row ${o.id===state.selected?"selected":""}`;row.dataset.id=o.id;row.innerHTML=`<span class="shape-glyph">${o.shape[0].toUpperCase()}</span><span>${o.label}<small class="row-state"> ${o.motion.type}${o.audible?"":" / muted"}</small></span><span>${o.id}</span>`;el.append(row)}$("editor").hidden=!current();renderEditor()}
  function renderEditor(){const o=current();if(!o)return;$("editorTitle").textContent=`Obstacle ${o.label}`;$("obLabel").value=o.label;$("obShape").value=o.shape;$("obX").value=o.x.toFixed(2);$("obZ").value=o.z.toFixed(2);$("obHeading").value=Math.round(o.heading);$("obWidth").value=o.widthM;$("obDepth").value=o.depthM;$("obHeight").value=o.heightM;$("obAudible").checked=o.audible;$("obMotion").value=o.motion.type;const m=o.motion, fields=$("motionFields");const input=(key,label,val)=>`<label>${label}<input data-motion="${key}" type="number" step="0.1" value="${val}"></label>`;fields.innerHTML=m.type==="patrol"?input("startX","Start X",m.startX)+input("startZ","Start Z",m.startZ)+input("endX","End X",m.endX)+input("endZ","End Z",m.endZ)+input("speedMps","Speed m/s",m.speedMps):m.type==="orbit"?input("centerX","Center X",m.centerX)+input("centerZ","Center Z",m.centerZ)+input("radiusM","Radius m",m.radiusM)+input("angularSpeedDeg","Degrees/s",m.angularSpeedDeg):m.type==="approach"?input("speedMps","Speed m/s",m.speedMps)+input("stopDistanceM","Stop distance",m.stopDistanceM):""}
  function renderTelemetry(){const lines=[`mode: ${state.mode}`,`audio: ${audio.started?"started":"locked"}`,`motion: ${state.paused?"paused":"running"}`,`listener: x=${state.listener.x.toFixed(2)} z=${state.listener.z.toFixed(2)} heading=${deg(state.listener.heading).toFixed(1)}deg`,`obstacles: ${state.obstacles.length}`,`vOICe: ${state.frequencies.voiceLow}-${state.frequencies.voiceHigh}Hz`,`HRTF: ${state.frequencies.hrtfLow}-${state.frequencies.hrtfHigh}Hz`,""];for(const o of state.obstacles){const m=metrics(o);lines.push(`${o.id}: ${o.shape} az=${deg(m.relativeAzimuth).toFixed(1)}deg d=${m.distance.toFixed(2)}m rv=${m.radialVelocity.toFixed(3)}m/frame`,`  motion=${o.motion.type} front/back=${Math.cos(m.relativeAzimuth)>=0?"front":"back"} audible=${o.audible}`)}$("telemetry").textContent=lines.join("\n");if(sim.eventLogOpen)$("eventLog").textContent=sim.log.slice(-80).map(x=>JSON.stringify(x)).join("\n")}
  function renderAll(){drawRadar();drawPov();renderList();syncRanges();renderTelemetry()}
  function updateListener(dt){const speed=3*dt;const f={x:Math.sin(state.listener.heading),z:Math.cos(state.listener.heading)},r={x:Math.cos(state.listener.heading),z:-Math.sin(state.listener.heading)};if(sim.keys.has("w")){state.listener.x+=f.x*speed;state.listener.z+=f.z*speed}if(sim.keys.has("s")){state.listener.x-=f.x*speed;state.listener.z-=f.z*speed}if(sim.keys.has("a")){state.listener.x-=r.x*speed;state.listener.z-=r.z*speed}if(sim.keys.has("d")){state.listener.x+=r.x*speed;state.listener.z+=r.z*speed}if(sim.keys.has("q"))state.listener.heading-=dt*1.8;if(sim.keys.has("e"))state.listener.heading+=dt*1.8;state.listener.heading=wrap(state.listener.heading);state.listener.x=clamp(state.listener.x,-W+.25,W-.25);state.listener.z=clamp(state.listener.z,-W+.25,W-.25)}
  function frame(now){const raw=Math.min(.1,(now-sim.last)/1000);sim.last=now;sim.accumulator+=raw;while(sim.accumulator>=FIXED){updateListener(FIXED);for(const o of state.obstacles){o.prevDistance=Math.hypot(o.x-state.listener.x,o.z-state.listener.z);updateMotion(o,FIXED)}sim.accumulator-=FIXED}syncHrtfListener();audio.update();if(audio.baseline&&audio.baseline!==sim.lastBaseline){sim.lastBaseline=audio.baseline;audio.sweepStart=audio.ctx.currentTime}audio.sweepPhase=audio.ctx&&audio.started&&state.mode==="baseline"&&audio.sweepStart?clamp((audio.ctx.currentTime-audio.sweepStart)/1.05,0,1):0;if(now-sim.sample>250){sim.sample=now;for(const o of state.obstacles){const m=metrics(o);log("sample",{obstacleId:o.id,shape:o.shape,x:+o.x.toFixed(3),z:+o.z.toFixed(3),azimuthRad:+m.relativeAzimuth.toFixed(4),distanceM:+m.distance.toFixed(3),radialVelocity:+m.radialVelocity.toFixed(4)})}}renderAll();requestAnimationFrame(frame)}
  function bind(){
    $("startAudio").onclick=()=>audio.started?audio.stop():audio.start();$("modeBaseline").onclick=()=>{state.mode="baseline";$("modeBaseline").setAttribute("aria-pressed","true");$("modeHrtf").setAttribute("aria-pressed","false");log("mode_changed",{mode:state.mode})};$("modeHrtf").onclick=()=>{state.mode="hrtf";$("modeBaseline").setAttribute("aria-pressed","false");$("modeHrtf").setAttribute("aria-pressed","true");log("mode_changed",{mode:state.mode})};$("pauseMotion").onclick=()=>{state.paused=!state.paused;$("pauseMotion").textContent=state.paused?"Resume Motion":"Pause Motion";$("pauseMotion").setAttribute("aria-pressed",state.paused);log("motion_paused",{paused:state.paused})};$("resetScene").onclick=resetScene;$("addObstacle").onclick=()=>addObstacle();$("duplicateObstacle").onclick=duplicateObstacle;$("removeObstacle").onclick=removeObstacle;
    $("obstacleList").onclick=e=>{const row=e.target.closest(".obstacle-row");if(row){state.selected=row.dataset.id;renderAll()}};
    const simple={obLabel:"label",obX:"x",obZ:"z",obHeading:"heading",obWidth:"widthM",obDepth:"depthM",obHeight:"heightM"};for(const [id,key] of Object.entries(simple))$(id).onchange=e=>patchObstacle(key,e.target.value);$("obShape").onchange=e=>patchObstacle("shape",e.target.value);$("obAudible").onchange=e=>patchObstacle("audible",e.target.checked);$("obMotion").onchange=e=>motionPatch("type",e.target.value);$("motionFields").onchange=e=>{if(e.target.dataset.motion)motionPatch(e.target.dataset.motion,e.target.value)};
    for(const [id,key] of [["voiceLow","voiceLow"],["voiceHigh","voiceHigh"],["hrtfLow","hrtfLow"],["hrtfHigh","hrtfHigh"]])$(id).onchange=e=>{state.frequencies[key]=clamp(Number(e.target.value)||1,80,16000);syncRanges();log("frequency_range_changed",{frequencies:clone(state.frequencies)})};$("resetVoice").onclick=()=>{state.frequencies.voiceLow=VOICE_DEFAULT.low;state.frequencies.voiceHigh=VOICE_DEFAULT.high;syncRanges()};$("resetHrtf").onclick=()=>{state.frequencies.hrtfLow=HRTF_DEFAULT.low;state.frequencies.hrtfHigh=HRTF_DEFAULT.high;syncRanges()};
    $("exportScene").onclick=()=>{const blob=new Blob([JSON.stringify({...clone(state),selected:state.selected},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`hrtf-scene-v2-${Date.now()}.json`;a.click();URL.revokeObjectURL(a.href);log("scene_exported")};$("importScene").onclick=()=>$("sceneFile").click();$("sceneFile").onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=validScene(JSON.parse(reader.result));Object.assign(state,clone(parsed));audio.sync();$("alert").hidden=true;log("scene_imported",{obstacleCount:state.obstacles.length});renderAll()}catch(err){$("alert").textContent=err.message;$("alert").hidden=false}};reader.readAsText(file)};$("toggleLog").onclick=()=>{sim.eventLogOpen=!sim.eventLogOpen;$("eventLog").hidden=!sim.eventLogOpen;$("toggleLog").textContent=sim.eventLogOpen?"Hide Event Log":"Show Event Log"};
    window.addEventListener("keydown",e=>{const k=e.key.toLowerCase();if("wasdqe".includes(k)){sim.keys.add(k);e.preventDefault()}});window.addEventListener("keyup",e=>sim.keys.delete(e.key.toLowerCase()));
    sceneCanvas.addEventListener("pointerdown",e=>{const r=sceneCanvas.getBoundingClientRect(),x=(e.clientX-r.left)*sceneCanvas.width/r.width,y=(e.clientY-r.top)*sceneCanvas.height/r.height;let hit=null;for(const o of state.obstacles){const p=worldToRadar(o.x,o.z);if(Math.hypot(x-p.x,y-p.y)<28)hit=o}if(hit){state.selected=hit.id;sim.drag={type:"obstacle",id:hit.id}}else sim.drag={type:"heading",lastX:e.clientX};sceneCanvas.setPointerCapture(e.pointerId);renderAll()});sceneCanvas.addEventListener("pointermove",e=>{if(!sim.drag)return;const r=sceneCanvas.getBoundingClientRect();if(sim.drag.type==="obstacle"){const o=state.obstacles.find(x=>x.id===sim.drag.id);if(o){const scale=sceneCanvas.width/(W*2);o.x=clamp((e.clientX-r.left)*sceneCanvas.width/r.width/scale-W+state.listener.x,-W+.25,W-.25);o.z=clamp(W-(e.clientY-r.top)*sceneCanvas.height/r.height/scale+state.listener.z,-W+.25,W-.25);}}else{state.listener.heading=wrap(state.listener.heading+(e.clientX-sim.drag.lastX)*.006);sim.drag.lastX=e.clientX}});window.addEventListener("pointerup",()=>sim.drag=null);
  }
  bind();syncAudioButton();renderAll();requestAnimationFrame(frame);
  window.HrtfLab={state,resetScene,addObstacle,removeObstacle,metrics,buildVoiceImage};
})();
